### PR TITLE
Update to readable-stream 3.0.0

### LINKED ISSUE #17: Update to readable-stream@3
It's holding webpack back at `readable-stream@2`.

Also, just genuinely curious... what is this module shimming that isn't provided by `readable-stream`?
I noticed this curiosity in `node-libs-browser` (Webpack's native Node shims):

```js
exports.stream			= require.resolve('stream-browserify');
exports._stream_duplex		= require.resolve('readable-stream/duplex.js');
exports._stream_passthrough	= require.resolve('readable-stream/passthrough.js');
exports._stream_readable	= require.resolve('readable-stream/readable.js');
exports._stream_transform	= require.resolve('readable-stream/transform.js');
exports._stream_writable	= require.resolve('readable-stream/writable.js');
```

Why don't they just use
```js
exports.stream			= require.resolve('readable-stream');
```

### LINKED ISSUE #22: Missing pipeline and finished implementation
The following functions exported by node's stream module seems to be missing:
   * `pipeline` https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback
   * `finished` https://nodejs.org/api/stream.html#stream_stream_finished_stream_options_callback

### LINKED ISSUE #24: readable-stream@2 mutates core-util-is
The current used version of `readable-stream` (v2) mutates the exports of `core-util-is`.

This is likely not intentional, but the side effect of a poorly constructed polyfill

```js
/*<replacement>*/
var util = require('core-util-is');
util.inherits = require('inherits');
/*</replacement>*/
```

I'm building a [plugin for browserify](github.com/lavamoat/overview) to reduce the risk of software supplychain attacks from the dependency graph. One of its protections is that is prevents the `module.exports` being mutated externally.

While I have seen this pattern with modules within a package, I haven't seen this pattern across packages, with the exception of this old version of `readable-stream`

I have verified this is resolved in v3

### PR DESCRIPTION
**Pull request by goto-bus-stop**
Closes #17 
Closes #22
Closes #24

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
rs@3 is significantly different in the browser and in node so we probably need some browserified tests here. it also drops support for some browser versions but i think its support is now the same as Buffer's so that's ok.

**Comment by huochunpeng** [comment]
Anyone reviewing this? readable-stream v3 is now 3.0.6 btw.

**Comment by goto-bus-stop** [comment]
there are still some problems with this unfortunately. i had some runtime crashes involving `util.inspect.custom` (which IIRC is not yet available in browserify's util)

**Comment by arahmanan** [comment]
@goto-bus-stop I believe there have been some changes with the use of `util.inspect.custom` in the more recent versions of `readable-stream` (starting from v.3.1.0). Do those address the issues you were running into? Let me know if I can help in any way.

**Comment by goto-bus-stop** [comment]
@arahmanan it looks like it! that means this should _almost_ be ready. i requested a saucelabs.com account for browserify so we can add some browser tests, i would like to be a bit more certain about what we support. especially because readable-stream now has slight implementation differences in the browser version and the node.js version for compatibility reasons. once that's set up, this can finally be released :)

**Comment by goto-bus-stop** [comment]
status update: saucelabs approved the request quickly, but I ran into some trouble claiming it. I only just finally emailed them about it, hopefully it can be resolved soon!

**Comment by guybedford** [comment]
@goto-bus-stop would you consider forking and publishing this update yourself? I'm currently looking into updating these builtins in jspm (https://github.com/jspm/jspm-core) and this would be great to avoid the duplication that now comes into effect since `http` has upgraded.

**Comment by goto-bus-stop** [comment]
Saucelabs says yes! :package: `stream-browserify@3.0.0`

**Comment by guybedford** [comment]
Amazing, persistence pays off :)

**Pull request merged**
