### PR TITLE
use stream3

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by feross** [comment]
I can't see any harm in merging this. @substack? Should be okay if we bump the browserify major?

**Comment by substack** [comment]
This is probably a good idea. Are there any other pieces we need to update at the same time?

**Comment by substack** [comment]
Unfortunately the test/crypto.js and test/crypto_ig.js tests in browserify core fail with streams3:

```
      TypeError: evalmachine.<anonymous>:15118
          ctor.prototype = Object.create(superCtor.prototype, {
                                                  ^
      Cannot read property 'prototype' of undefined
```

This error looks like a cyclic dependency issue.

**Comment by stevemao** [comment]
I'll find time and have a look. Probably will copy the stream code in iojs.

**Pull request merged**
