### PR TITLE
jspm Node support

### PR DESCRIPTION
**Pull request by guybedford**
See https://github.com/substack/https-browserify/pull/4.

### CODE REVIEW

**Comment by stevemao** [comment]
Looking at the changes you made for other browserify packages, the naming seems to be very consistent. I presume you need the same mapping for non-browserify packages? If the naming is consistent why do you need it for every single package?

**Comment by guybedford** [comment]
https://github.com/crypto-browserify/crypto-browserify/pull/144#issuecomment-160735802 may clarify - this is specifically to replace browserify packages with their Node core equivalents.

**Comment by stevemao** [comment]
Oh I see.

**Comment by guybedford** [comment]
Let me know if this still might be possible or if you have any further questions at all?

**Comment by stevemao** [comment]
It's up to @substack @feross and other core browserify developers

**Comment by guybedford** [comment]
I can work around this.

**Pull request closed without merging**
